# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-09-01 10:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OroWebhook', '0002_auto_20170731_1011'),
    ]

    operations = [
        migrations.AddField(
            model_name='lastquestion',
            name='tries',
            field=models.TextField(default=b'0'),
        ),
    ]
